os:
  - linux

script:
  - "docker-compose up --build -d dev"
  - "docker-compose exec dev ./build.sh"
  - "docker-compose exec dev echo \"Running imaginary tests\""
  - "docker-compose down"

deploy:
  skip_cleanup: true
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

# Encrypted Docker Hub password
env:
  global:
    secure: "CHZyapDKvBRS6ETSNQTb2OK8iSBmqMrCEVKbwh1MnjZoJUfk8LEoF0bbY0NJK//0oGoKm5RQBxspIbgzp4WWGRwt0WlGe9EcRuRtH1jSCi7YXmSMhQFxeQM7TU3WvVsnYO8FPYD0LIghnuJ2KPOUX28lQiPFYTGM18v1ig5+E87EjCwJD+BkvnlpwwXHiwUyBlYpPandIyTEkOEzoqV+4KjLDobMhdtGRTWKxIhnKec19j7wAClcblybn6mn1zqY6WAst/DOJSpmDmyifT+A3f9bnZRaarLoa7Eei38XRHS8JLSPZ+Sf1hd2ipAesw6BGehOq6+aftLuqIgPVeTfzjNWhqYgdpkyXitaNzmG6PtGDlIfkgED5HVR2X5401ro9zD2BSVCabYDxlU1bW1PMEhToOFmJCpPj0qPCzx17nEtWfgzpMc4bjbvFRNeMzyEqhId8/tfDG/L73lpCi3u8pyECZWOtha19CjJW6f8qemVq6KWV1pkIrfzfNe2Dyss3Mkv25kvBgYR+1QvoReu4DYWmMYh+3c84DNWMVvEATRmit3tZjMIfap0DJEKhGR0HV2+QgTfz6yJMnPXRmOhcFuxnw3YuPwBX9D+AGNrBZ3ezrAqqnhWZ29kj+GTTKEcU9uWoTbzUz1w7MTWWx3HKDh5wiM8Xv+Qml14mOkiPdQ="
