version: '3.2'

services:
  dev:
    build: 
      context: .devcontainer
      cache_from:
        - ghcr.io/uas-at-ucla/docker-paradigm-dev
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: ghcr.io/uas-at-ucla/docker-paradigm-dev
    container_name: docker-paradigm-dev
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    # more_run_options_go_here:
    
  prod:
    build:
      context: .
      dockerfile: prod.Dockerfile
    image: ghcr.io/uas-at-ucla/docker-paradigm
