# Change to desired base image. The digest (the part that starts with @sha256) isn't strictly necessary, but it ensures that the base image is always the same to prevent unnecessary rebuilds.
FROM debian:10@sha256:b1feef0e231d159a8d9d9524ac507f2488e34d032421368830efb08ad5038f16

# Do stuff here

WORKDIR /workspace
