name: CI-master

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  # Run tests.
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

#       - name: Force-build Docker container from scratch. Only required prior to first image upload.
#         run: docker-compose build dev

      - name: Start Docker container
        run: docker-compose up --build -d dev
        
      - name: Build code
        run: docker-compose exec -T dev ./build.sh

      - name: Run tests
        run: docker-compose exec -T dev echo "Running imaginary tests"

      - name: Stop Docker container
        run: docker-compose down

  # Push image to Docker Hub.
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    env:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - name: Push Docker images
        run: ./docker_push.sh
